apiVersion: v1
kind: PersistentVolumeClaim
namespace: argocd
metadata:
  name: dev1-pvc
spec: 
  storageClassName: dev1-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
